import React from 'react'
import { Icon, Label } from 'semantic-ui-react'

export const colors = [{
          key: 'green',
          text: <Label circular color='green'/>,
          value: 'GREEN'
      },
      {
          key: 'red',
          text: <Label circular color='red'/>,
          value: 'RED'
      },
      {
          key: 'purple',
          text: <Label circular color='purple'/>,
          value: 'PURPLE'
      },
      {
          key: 'pink',
          text: <Label circular color='pink'/>,
          value: 'PINK'
      },
      {
          key: 'orange',
          text: <Label circular color='orange'/>,
          value: 'ORANGE'
      },
      {
          key: 'yellow',
          text: <Label circular color='yellow'/>,
          value: 'YELLOW'
      },
      {
          key: 'grey',
          text: <Label circular color='grey'/>,
          value: 'GREY'
      }]

export const priorities = [{
          key: 'normal',
          text: <Icon fitted name='exclamation'/>,
          value: 'normal'
      },
      {
          key: 'high',
          text: <span><Icon fitted name='exclamation'/><Icon fitted name='exclamation'/></span>,
          value: 'high'
      },
      {
          key: 'urgent',
          text: <span><Icon fitted name='exclamation'/><Icon fitted name='exclamation'/><Icon fitted name='exclamation'/></span>,
          value: 'urgent'
      }
  ]


export const genders = [{
        key: 'male',
        text: 'Male',
        value: 'male'
    },
    {
        key: 'female',
        text: 'Female',
        value: 'female'
    },
    {
        key: 'other',
        text: 'Other',
        value: 'other'
    }
]

export const countries = [
  { key: 'af',      text: 'Afghanistan'                 , value: 'af' },
  { key: 'ax',      text: 'Aland Islands'               , value: 'ax' },
  { key: 'al',      text: 'Albania'                     , value: 'al' },
  { key: 'dz',      text: 'Algeria'                     , value: 'dz' },
  { key: 'as',      text: 'American Samoa'              , value: 'as' },
  { key: 'ad',      text: 'Andorra'                     , value: 'ad' },
  { key: 'ao',      text: 'Angola'                      , value: 'ao' },
  { key: 'ai',      text: 'Anguilla'                    , value: 'ai' },
  { key: 'ag',      text: 'Antigua'                     , value: 'ag' },
  { key: 'ar',      text: 'Argentina'                   , value: 'ar' },
  { key: 'am',      text: 'Armenia'                     , value: 'am' },
  { key: 'aw',      text: 'Aruba'                       , value: 'aw' },
  { key: 'au',      text: 'Australia'                   , value: 'au' },
  { key: 'at',      text: 'Austria'                     , value: 'at' },
  { key: 'az',      text: 'Azerbaijan'                  , value: 'az' },
  { key: 'bs',      text: 'Bahamas'                     , value: 'bs' },
  { key: 'bh',      text: 'Bahrain'                     , value: 'bh' },
  { key: 'bd',      text: 'Bangladesh'                  , value: 'bd' },
  { key: 'bb',      text: 'Barbados'                    , value: 'bb' },
  { key: 'by',      text: 'Belarus'                     , value: 'by' },
  { key: 'be',      text: 'Belgium'                     , value: 'be' },
  { key: 'bz',      text: 'Belize'                      , value: 'bz' },
  { key: 'bj',      text: 'Benin'                       , value: 'bj' },
  { key: 'bm',      text: 'Bermuda'                     , value: 'bm' },
  { key: 'bt',      text: 'Bhutan'                      , value: 'bt' },
  { key: 'bo',      text: 'Bolivia'                     , value: 'bo' },
  { key: 'ba',      text: 'Bosnia'                      , value: 'ba' },
  { key: 'bw',      text: 'Botswana'                    , value: 'bw' },
  { key: 'bv',      text: 'Bouvet Island'               , value: 'bv' },
  { key: 'br',      text: 'Brazil'                      , value: 'br' },
  { key: 'vg',      text: 'British Virgin Islands'      , value: 'vg' },
  { key: 'bn',      text: 'Brunei'                      , value: 'bn' },
  { key: 'bg',      text: 'Bulgaria'                    , value: 'bg' },
  { key: 'bf',      text: 'Burkina Faso'                , value: 'bf' },
  { key: 'mm',      text: 'Burma'                       , value: 'mm' },
  { key: 'bi',      text: 'Burundi'                     , value: 'bi' },
  { key: 'tc',      text: 'Caicos Islands'              , value: 'tc' },
  { key: 'kh',      text: 'Cambodia'                    , value: 'kh' },
  { key: 'cm',      text: 'Cameroon'                    , value: 'cm' },
  { key: 'ca',      text: 'Canada'                      , value: 'ca' },
  { key: 'cv',      text: 'Cape Verde'                  , value: 'cv' },
  { key: 'ky',      text: 'Cayman Islands'              , value: 'ky' },
  { key: 'cf',      text: 'Central African Republic'    , value: 'cf' },
  { key: 'td',      text: 'Chad'                        , value: 'td' },
  { key: 'cl',      text: 'Chile'                       , value: 'cl' },
  { key: 'cn',      text: 'China'                       , value: 'cn' },
  { key: 'cx',      text: 'Christmas Island'            , value: 'cx' },
  { key: 'cc',      text: 'Cocos Islands'               , value: 'cc' },
  { key: 'co',      text: 'Colombia'                    , value: 'co' },
  { key: 'km',      text: 'Comoros'                     , value: 'km' },
  { key: 'cd',      text: 'Congo'                       , value: 'cd' },
  { key: 'cg',      text: 'Congo Brazzaville'           , value: 'cg' },
  { key: 'ck',      text: 'Cook Islands'                , value: 'ck' },
  { key: 'cr',      text: 'Costa Rica'                  , value: 'cr' },
  { key: 'ci',      text: 'Cote Divoire'                , value: 'ci' },
  { key: 'hr',      text: 'Croatia'                     , value: 'hr' },
  { key: 'cu',      text: 'Cuba'                        , value: 'cu' },
  { key: 'cy',      text: 'Cyprus'                      , value: 'cy' },
  { key: 'cz',      text: 'Czech Republic'              , value: 'cz' },
  { key: 'dk',      text: 'Denmark'                     , value: 'dk' },
  { key: 'dj',      text: 'Djibouti'                    , value: 'dj' },
  { key: 'dm',      text: 'Dominica'                    , value: 'dm' },
  { key: 'do',      text: 'Dominican Republic'          , value: 'do' },
  { key: 'ec',      text: 'Ecuador'                     , value: 'ec' },
  { key: 'eg',      text: 'Egypt'                       , value: 'eg' },
  { key: 'sv',      text: 'El Salvador'                 , value: 'sv' },
  { key: 'gq',      text: 'Equatorial Guinea'           , value: 'gq' },
  { key: 'er',      text: 'Eritrea'                     , value: 'er' },
  { key: 'ee',      text: 'Estonia'                     , value: 'ee' },
  { key: 'et',      text: 'Ethiopia'                    , value: 'et' },
  { key: 'eu',      text: 'Europeanunion'               , value: 'eu' },
  { key: 'fk',      text: 'Falkland Islands'            , value: 'fk' },
  { key: 'fo',      text: 'Faroe Islands'               , value: 'fo' },
  { key: 'fj',      text: 'Fiji'                        , value: 'fj' },
  { key: 'fi',      text: 'Finland'                     , value: 'fi' },
  { key: 'fr',      text: 'France'                      , value: 'fr' },
  { key: 'gf',      text: 'French Guiana'               , value: 'gf' },
  { key: 'pf',      text: 'French Polynesia'            , value: 'pf' },
  { key: 'tf',      text: 'French Territories'          , value: 'tf' },
  { key: 'ga',      text: 'Gabon'                       , value: 'ga' },
  { key: 'gm',      text: 'Gambia'                      , value: 'gm' },
  { key: 'ge',      text: 'Georgia'                     , value: 'ge' },
  { key: 'de',      text: 'Germany'                     , value: 'de' },
  { key: 'gh',      text: 'Ghana'                       , value: 'gh' },
  { key: 'gi',      text: 'Gibraltar'                   , value: 'gi' },
  { key: 'gr',      text: 'Greece'                      , value: 'gr' },
  { key: 'gl',      text: 'Greenland'                   , value: 'gl' },
  { key: 'gd',      text: 'Grenada'                     , value: 'gd' },
  { key: 'gp',      text: 'Guadeloupe'                  , value: 'gp' },
  { key: 'gu',      text: 'Guam'                        , value: 'gu' },
  { key: 'gt',      text: 'Guatemala'                   , value: 'gt' },
  { key: 'gn',      text: 'Guinea'                      , value: 'gn' },
  { key: 'gw',      text: 'Guinea-Bissau'               , value: 'gw' },
  { key: 'gy',      text: 'Guyana'                      , value: 'gy' },
  { key: 'ht',      text: 'Haiti'                       , value: 'ht' },
  { key: 'hm',      text: 'Heard Island'                , value: 'hm' },
  { key: 'hn',      text: 'Honduras'                    , value: 'hn' },
  { key: 'hk',      text: 'Hong Kong'                   , value: 'hk' },
  { key: 'hu',      text: 'Hungary'                     , value: 'hu' },
  { key: 'is',      text: 'Iceland'                     , value: 'is' },
  { key: 'in',      text: 'India'                       , value: 'in' },
  { key: 'io',      text: 'Indian Ocean Territory'      , value: 'io' },
  { key: 'id',      text: 'Indonesia'                   , value: 'id' },
  { key: 'ir',      text: 'Iran'                        , value: 'ir' },
  { key: 'iq',      text: 'Iraq'                        , value: 'iq' },
  { key: 'ie',      text: 'Ireland'                     , value: 'ie' },
  { key: 'il',      text: 'Israel'                      , value: 'il' },
  { key: 'it',      text: 'Italy'                       , value: 'it' },
  { key: 'jm',      text: 'Jamaica'                     , value: 'jm' },
  { key: 'sj',      text: 'Jan Mayen'                   , value: 'sj' },
  { key: 'jp',      text: 'Japan'                       , value: 'jp' },
  { key: 'jo',      text: 'Jordan'                      , value: 'jo' },
  { key: 'kz',      text: 'Kazakhstan'                  , value: 'kz' },
  { key: 'ke',      text: 'Kenya'                       , value: 'ke' },
  { key: 'ki',      text: 'Kiribati'                    , value: 'ki' },
  { key: 'kw',      text: 'Kuwait'                      , value: 'kw' },
  { key: 'kg',      text: 'Kyrgyzstan'                  , value: 'kg' },
  { key: 'la',      text: 'Laos'                        , value: 'la' },
  { key: 'lv',      text: 'Latvia'                      , value: 'lv' },
  { key: 'lb',      text: 'Lebanon'                     , value: 'lb' },
  { key: 'ls',      text: 'Lesotho'                     , value: 'ls' },
  { key: 'lr',      text: 'Liberia'                     , value: 'lr' },
  { key: 'ly',      text: 'Libya'                       , value: 'ly' },
  { key: 'li',      text: 'Liechtenstein'               , value: 'li' },
  { key: 'lt',      text: 'Lithuania'                   , value: 'lt' },
  { key: 'lu',      text: 'Luxembourg'                  , value: 'lu' },
  { key: 'mo',      text: 'Macau'                       , value: 'mo' },
  { key: 'mk',      text: 'Macedonia'                   , value: 'mk' },
  { key: 'mg',      text: 'Madagascar'                  , value: 'mg' },
  { key: 'mw',      text: 'Malawi'                      , value: 'mw' },
  { key: 'my',      text: 'Malaysia'                    , value: 'my' },
  { key: 'mv',      text: 'Maldives'                    , value: 'mv' },
  { key: 'ml',      text: 'Mali'                        , value: 'ml' },
  { key: 'mt',      text: 'Malta'                       , value: 'mt' },
  { key: 'mh',      text: 'Marshall Islands'            , value: 'mh' },
  { key: 'mq',      text: 'Martinique'                  , value: 'mq' },
  { key: 'mr',      text: 'Mauritania'                  , value: 'mr' },
  { key: 'mu',      text: 'Mauritius'                   , value: 'mu' },
  { key: 'yt',      text: 'Mayotte'                     , value: 'yt' },
  { key: 'mx',      text: 'Mexico'                      , value: 'mx' },
  { key: 'fm',      text: 'Micronesia'                  , value: 'fm' },
  { key: 'md',      text: 'Moldova'                     , value: 'md' },
  { key: 'mc',      text: 'Monaco'                      , value: 'mc' },
  { key: 'mn',      text: 'Mongolia'                    , value: 'mn' },
  { key: 'me',      text: 'Montenegro'                  , value: 'me' },
  { key: 'ms',      text: 'Montserrat'                  , value: 'ms' },
  { key: 'ma',      text: 'Morocco'                     , value: 'ma' },
  { key: 'mz',      text: 'Mozambique'                  , value: 'mz' },
  { key: 'na',      text: 'Namibia'                     , value: 'na' },
  { key: 'nr',      text: 'Nauru'                       , value: 'nr' },
  { key: 'np',      text: 'Nepal'                       , value: 'np' },
  { key: 'nl',      text: 'Netherlands'                 , value: 'nl' },
  { key: 'an',      text: 'Netherlandsantilles'         , value: 'an' },
  { key: 'nc',      text: 'New Caledonia'               , value: 'nc' },
  { key: 'pg',      text: 'New Guinea'                  , value: 'pg' },
  { key: 'nz',      text: 'New Zealand'                 , value: 'nz' },
  { key: 'ni',      text: 'Nicaragua'                   , value: 'ni' },
  { key: 'ne',      text: 'Niger'                       , value: 'ne' },
  { key: 'ng',      text: 'Nigeria'                     , value: 'ng' },
  { key: 'nu',      text: 'Niue'                        , value: 'nu' },
  { key: 'nf',      text: 'Norfolk Island'              , value: 'nf' },
  { key: 'kp',      text: 'North Korea'                 , value: 'kp' },
  { key: 'mp',      text: 'Northern Mariana Islands'    , value: 'mp' },
  { key: 'no',      text: 'Norway'                      , value: 'no' },
  { key: 'om',      text: 'Oman'                        , value: 'om' },
  { key: 'pk',      text: 'Pakistan'                    , value: 'pk' },
  { key: 'pw',      text: 'Palau'                       , value: 'pw' },
  { key: 'ps',      text: 'Palestine'                   , value: 'ps' },
  { key: 'pa',      text: 'Panama'                      , value: 'pa' },
  { key: 'py',      text: 'Paraguay'                    , value: 'py' },
  { key: 'pe',      text: 'Peru'                        , value: 'pe' },
  { key: 'ph',      text: 'Philippines'                 , value: 'ph' },
  { key: 'pn',      text: 'Pitcairn Islands'            , value: 'pn' },
  { key: 'pl',      text: 'Poland'                      , value: 'pl' },
  { key: 'pt',      text: 'Portugal'                    , value: 'pt' },
  { key: 'pr',      text: 'Puerto Rico'                 , value: 'pr' },
  { key: 'qa',      text: 'Qatar'                       , value: 'qa' },
  { key: 're',      text: 'Reunion'                     , value: 're' },
  { key: 'ro',      text: 'Romania'                     , value: 'ro' },
  { key: 'ru',      text: 'Russia'                      , value: 'ru' },
  { key: 'rw',      text: 'Rwanda'                      , value: 'rw' },
  { key: 'sh',      text: 'Saint Helena'                , value: 'sh' },
  { key: 'kn',      text: 'Saint Kitts and Nevis'       , value: 'kn' },
  { key: 'lc',      text: 'Saint Lucia'                 , value: 'lc' },
  { key: 'pm',      text: 'Saint Pierre'                , value: 'pm' },
  { key: 'vc',      text: 'Saint Vincent'               , value: 'vc' },
  { key: 'ws',      text: 'Samoa'                       , value: 'ws' },
  { key: 'sm',      text: 'San Marino'                  , value: 'sm' },
  { key: 'gs',      text: 'Sandwich Islands'            , value: 'gs' },
  { key: 'st',      text: 'Sao Tome'                    , value: 'st' },
  { key: 'sa',      text: 'Saudi Arabia'                , value: 'sa' },
  { key: 'gb sct',  text: 'Scotland'                    , value: 'gb sct' },
  { key: 'sn',      text: 'Senegal'                     , value: 'sn' },
  { key: 'cs',      text: 'Serbia'                      , value: 'cs' },
  { key: 'rs',      text: 'Serbia'                      , value: 'rs' },
  { key: 'sc',      text: 'Seychelles'                  , value: 'sc' },
  { key: 'sl',      text: 'Sierra Leone'                , value: 'sl' },
  { key: 'sg',      text: 'Singapore'                   , value: 'sg' },
  { key: 'sk',      text: 'Slovakia'                    , value: 'sk' },
  { key: 'si',      text: 'Slovenia'                    , value: 'si' },
  { key: 'sb',      text: 'Solomon Islands'             , value: 'sb' },
  { key: 'so',      text: 'Somalia'                     , value: 'so' },
  { key: 'za',      text: 'South Africa'                , value: 'za' },
  { key: 'kr',      text: 'South Korea'                 , value: 'kr' },
  { key: 'es',      text: 'Spain'                       , value: 'es' },
  { key: 'lk',      text: 'Sri Lanka'                   , value: 'lk' },
  { key: 'sd',      text: 'Sudan'                       , value: 'sd' },
  { key: 'sr',      text: 'Suriname'                    , value: 'sr' },
  { key: 'sz',      text: 'Swaziland'                   , value: 'sz' },
  { key: 'se',      text: 'Sweden'                      , value: 'se' },
  { key: 'ch',      text: 'Switzerland'                 , value: 'ch' },
  { key: 'sy',      text: 'Syria'                       , value: 'sy' },
  { key: 'tw',      text: 'Taiwan'                      , value: 'tw' },
  { key: 'tj',      text: 'Tajikistan'                  , value: 'tj' },
  { key: 'tz',      text: 'Tanzania'                    , value: 'tz' },
  { key: 'th',      text: 'Thailand'                    , value: 'th' },
  { key: 'tl',      text: 'Timorleste'                  , value: 'tl' },
  { key: 'tg',      text: 'Togo'                        , value: 'tg' },
  { key: 'tk',      text: 'Tokelau'                     , value: 'tk' },
  { key: 'to',      text: 'Tonga'                       , value: 'to' },
  { key: 'tt',      text: 'Trinidad'                    , value: 'tt' },
  { key: 'tn',      text: 'Tunisia'                     , value: 'tn' },
  { key: 'tr',      text: 'Turkey'                      , value: 'tr' },
  { key: 'tm',      text: 'Turkmenistan'                , value: 'tm' },
  { key: 'tv',      text: 'Tuvalu'                      , value: 'tv' },
  { key: 'ae',      text: 'U.A.E.'                      , value: 'ae' },
  { key: 'ug',      text: 'Uganda'                      , value: 'ug' },
  { key: 'ua',      text: 'Ukraine'                     , value: 'ua' },
  { key: 'gb',      text: 'United Kingdom'              , value: 'gb' },
  { key: 'us',      text: 'United States'               , value: 'us' },
  { key: 'uy',      text: 'Uruguay'                     , value: 'uy' },
  { key: 'um',      text: 'US Minor Islands'            , value: 'um' },
  { key: 'vi',      text: 'US Virgin Islands'           , value: 'vi' },
  { key: 'uz',      text: 'Uzbekistan'                  , value: 'uz' },
  { key: 'vu',      text: 'Vanuatu'                     , value: 'vu' },
  { key: 'va',      text: 'Vatican City'                , value: 'va' },
  { key: 've',      text: 'Venezuela'                   , value: 've' },
  { key: 'vn',      text: 'Vietnam'                     , value: 'vn' },
  { key: 'gb wls',  text: 'Wales'                       , value: 'gb wls' },
  { key: 'wf',      text: 'Wallis and Futuna'           , value: 'wf' },
  { key: 'eh',      text: 'Western Sahara'              , value: 'eh' },
  { key: 'ye',      text: 'Yemen'                       , value: 'ye' },
  { key: 'zm',      text: 'Zambia'                      , value: 'zm' },
  { key: 'zw',      text: 'Zimbabwe'                    , value: 'zw' },
]